### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by binary64** [sqhtiamo/webpack-sftp-client#5]
```
new WebpackSftpClient({
      port: '2222',
      host: 'xxx',
      username: 'xxx',
      password: 'xxx',
      path: './build/',
      remotePath: '/public_html/react/',
      // Show details of uploading for files
      verbose: true
    }),
```

Produces:

```
Transfer ./build/index.html => /public_html/react/index.html
Transfer ./build/main.7b35982842fa71b3c204.js => /public_html/react/main.7b35982842fa71b3c204.js/main.7b35982842fa71b3c204.js
C:\p\berton-react\node_modules\ssh2-streams\lib\sftp.js:878
    throw new Error('handle is not a Buffer');
    ^

Error: handle is not a Buffer
    at SFTPStream.writeData (C:\p\berton-react\node_modules\ssh2-streams\lib\sftp.js:878:11)
    at SFTPWrapper.write (C:\p\berton-react\node_modules\ssh2\lib\SFTPWrapper.js:48:23)
    at C:\p\berton-react\node_modules\scp2\lib\client.js:216:18
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! berton-test@0.0.0 build: `cross-env NODE_ENV=production webpack  --progress`
npm ERR! Exit status 1
```

**Comment by binary64** [comment]
I see the error - on this line:

`Transfer ./build/main.7b35982842fa71b3c204.js => /public_html/react/main.7b35982842fa71b3c204.js/main.7b35982842fa71b3c204.js`

You can see it's trying to put the file into a directory named after itself. Looks like a simple bug..

**Comment by sqhtiamo** [comment]
@binary64 Thanks for your feedback, and I will fix it later.
